#!/usr/bin/env bash

shopt -s expand_aliases


# This file contains aliases and functions that duplicate some fish
# functionality, because Vim will use bash as its external command shell.

AG_BIN="`which ag`"
function ag() {
    if test -f '.agignore' && grep -q 'pragma: skipvcs' '.agignore'; then
        $AG_BIN --search-files -U "$@"
    else
        $AG_BIN --search-files "$@"
    fi
}

export PATH=~/bin:~/src/dotfiles/bin:~/src/dotfiles/lisp/binaries:/usr/local/share/python:/usr/local/bin/:$PATH

alias h='hg'
alias g='git'
alias pj='python -m json.tool'
alias pbc='pbcopy'
alias pbp='pbpaste'
alias pbpb='pbp | pb'
alias vu='vagrant up'
alias vs='vagrant suspend'
alias o='open'
alias oo='open .'

function psg() {
    ps auxww | grep --color=always $* | grep -v grep | collapse | cuts -f 2,11-
}

GPG_TTY=`tty`
export GPG_TTY
